export const usersStore = {
  data: [
    {
      id: 1,
      name: "Luiz Henrique",
      email: "luiz@gmail.com",
      cpf: "123.456.789-00",
      plan: "12 meses",
      status: "Ativo",
      workouts: 18,
      calories: 12400,
      frequency: "Alta",
      protein: 120,
      water: 2.5,
      lastWorkout: "Full Body",
      lastClass: "Boxing",
    },
    {
      id: 2,
      name: "João Silva",
      email: "joao@gmail.com",
      cpf: "222.333.444-55",
      plan: "6 meses",
      status: "Ativo",
      workouts: 10,
      calories: 8000,
      frequency: "Média",
      protein: 90,
      water: 2.0,
      lastWorkout: "Upper Body",
      lastClass: "Yoga",
    },
    {
      id: 3,
      name: "Maria Souza",
      email: "maria@gmail.com",
      cpf: "999.888.777-66",
      plan: "1 mês",
      status: "Inativo",
      workouts: 5,
      calories: 3000,
      frequency: "Baixa",
      protein: 70,
      water: 1.5,
      lastWorkout: "Cardio",
      lastClass: "Pilates",
    },
  ],
};